string[] coordenadas = Console.ReadLine().Split();
double X = double.Parse(coordenadas[0]);
double Y = double.Parse(coordenadas[1]);
if ( X == 0 && Y == 0 ) Console.WriteLine("Origem");
else if ( X != 0 && Y == 0 ) Console.WriteLine("Eixo X");
else if ( X == 0 && Y != 0 ) Console.WriteLine("Eixo Y");
else if ( X > 0 && Y > 0 ) Console.WriteLine("Q1");
else if ( X < 0 && Y > 0 ) Console.WriteLine("Q2");
else if ( X < 0 && Y < 0 ) Console.WriteLine("Q3");
else Console.WriteLine("Q4");